### ISSUE TITLE
index.ejs gives type error

### ISSUE THREAD

**Issue by subba2048** [achowba/node-mysql-crud-app#2]

**Comment by rjkhan** [comment]
i have also had the same isuee i tried with ejs-lint engine. but still there is error

"SyntaxError: Unexpected identifier in /Users/rabnawazjansher/Documents/Node-app/Crud-app/views/index.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/rabnawazjansher/Documents/Node-app/Crud-app/node_modules/ejs/lib/ejs.js:626:12)
    at Object.compile (/Users/rabnawazjansher/Documents/Node-app/Crud-app/node_modules/ejs/lib/ejs.js:366:16)
    at handleCache (/Users/rabnawazjansher/Documents/Node-app/Crud-app/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/Users/rabnawazjansher/Documents/Node-app/Crud-app/node_modules/ejs/lib/ejs.js:254:16)
    at View.exports.renderFile [as engine] (/Users/rabnawazjansher/Documents/Node-app/Crud-app/node_modules/ejs/lib/ejs.js:459:10)
    at View.render (/Users/rabnawazjansher/Documents/Node-app/Crud-app/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/rabnawazjansher/Documents/Node-app/Crud-app/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/rabnawazjansher/Documents/Node-app/Crud-app/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/rabnawazjansher/Do"

>
